### ISSUE TITLE
vnclog output is 0 bytes

### ISSUE THREAD

**Issue by sibeshkar** [sibson/vncdotool#140]
Have you included the following information?

 - [x] VNC server and version

Xvnc TigerVNC version 1.8.0

 - [x] vncdotool version

vncdotool 0.12.1

 - [x] steps to reproduce
1. Run this docker command to start vnc server in ubuntu docker container with unity environment.
```
sudo docker run -itd -p 84:6080 -p 92:5901 -p 95:95 -e PASSWORD=password -e SUDO=yes chenjr0719/ubuntu-unity-novnc
```
2. Exec into docker container, `sudo apt-get update`, `sudo apt-get install python-pip`
3. Install vncdotool in container: `sudo pip install vncdotool`
4. Run this in container : 
```
vnclog -s 127.0.0.1::5901 -p boxware --password-required --listen 95 -v keylog.vdo
```
5. Outside the container, open VNC viewer and connect to `127.0.0.1::95` with password : 'password'

Output of running vnlog loop: 
```
INFO:twisted:VNCLoggingServerFactory starting on 95
INFO:twisted:Starting factory <vncdotool.loggingproxy.VNCLoggingServerFactory instance at 0x7fa45413de60>
INFO:proxy:new connection from 172.17.0.1
INFO:twisted:Starting factory <vncdotool.loggingproxy.VNCLoggingClientFactory instance at 0x7fa454143e18>
```
6. [do things with keyboard and mouse]
7. Go inside container, do `cat keylog.vdo`
8. `keylog.vdo` is zero bytes, nothing is logged.

**Comment by sibson** [comment]
Have you terminated the connection or vnclog process? If not then my guess is the OS output buffer isn't being flushed before you run cat, in which case running [sync](https://linux.die.net/man/8/sync) before ```cat``` should solve the issue.

**Comment by sibeshkar** [comment]
Still no luck. Have tried terminating both connection and vnclog process before running `cat keylog.vdo`. Running `sync` during a connection doesn't help either. Was it possible for you to reproduce this error? Is there some specific way to debug this?

**Comment by Paulynz** [comment]
Good day! Any update of this? vnclog not logging at all.
