### ISSUE TITLE
auth failed issue

### ISSUE THREAD

**Issue by CharlesJQuarra** [sibson/vncdotool#96]
I'm running this snippet on Mac OS X 10.10

```
from vncdotool import api

client = api.connect('192.168.99.100::5901', password='vncpassword')

client.captureScreen('screenshot.png')
client.disconnect()
```
The vnc host is a docker image created from this [docker vnc project](https://github.com/ConSol/docker-headless-vnc-container)

I can login fine using vnc viewer, but running the test script above, I get a connection failed at line [193 of rfb.py](https://github.com/sibson/vncdotool/blob/master/vncdotool/rfb.py#L193)

Any idea what might be causing this trouble?

**Comment by HeavyThumper** [comment]
What version of vncdotool and Python are you running?  I'm having problems with 0.11.2 while 0.10.0 (on Python 2.7) works fine.

**Comment by epineda** [comment]
I have the same problem with 0.11.2 but with 0.10.0 works fine.

With 0.11.2 the verbose output was: (testing with vncdotool capture command) 
```
INFO:root:connecting to 192.168.241.128:5900
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x05C0D328>
INFO:twisted:Protocol version 3.800 not supported
INFO:twisted:Using protocol version 3.300
INFO:twisted:Cannot connect authentication failed
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x05C0D328>
INFO:twisted:Main loop terminated.

```

I'm using python 2.7.13

With 0.10.0 the verbose output was:
```
INFO:root:connecting to 192.168.241.128:5900
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x05D142D8>
INFO:twisted:Protocol version 3.800 not supported
INFO:twisted:Using protocol version 3.300
INFO:root:connected to 2167d6e1ab13:99.0
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x05D142D8>
INFO:twisted:Main loop terminated.

```

**Comment by sibson** [comment]
This could have been fixed by #105, would be appreciated if anyone can confirm if master is working for them.  Also #102, might be a dupe.

**Comment by sibson** [comment]
Possibly fixed by https://github.com/sibson/vncdotool/pull/125, can anyone confirm?

**Comment by pmhahn** [comment]
I've taken a look and it still fails for me. Sadly the docker image mentioned above is broken for me: https://github.com/ConSol/docker-headless-vnc-container/issues/165

```sh
mkdir bug96
cat > ./bug96/Dockerfile <<__DOCKER__
FROM consol/debian-xfce-vnc
USER 0
RUN printf '$localhost = "no";\n1;\n' >/etc/tigervnc/vncserver-config-defaults
USER 1000
__DOCKER__
docker build -t debian-xfce-vnc ./bug96
docker run -d -p 5901:5901 --name bug96 debian-xfce-vnc

virtualenv v2
.  v2/bin/activate
pip install git+https://github.com/sibson/vncdotool.git@main
vncdotool -v -s 127.0.0.1:1 -p vncpassword capture bug96/screen.png
```
is still failing with
> INFO:twisted:Cannot connect b'Authentication failure'

`git bisect` from `v0.10.0` to `v0.11.0` fails at  659a9e327d5, but that is just the one breaking Python 2 backward compatibility.
- ✅ v0.11.0 with 659a9e327d5

**Comment by pmhahn** [comment]
As #234 has been merged I just re-checked it and now the issue is fixed for me.
Again: upstreams docker images are broken, you need to run a modified version **not** listening on `localhost` only inside the container.
